### ISSUE TITLE
Is this project work correctly?

### ISSUE THREAD

**Issue by yichaosun** [metanet/p2p#1]
hello bro,
I run this project follow your readme, and start two peer in my computer, with different port, but the command 'connect 127.0.0.1:50670' lead to an error，as follow :
Peer2 | 18:16:42.257 [main] ERROR com.basrikahveci.p2p.peer.PeerHandle - Command failed: connect 127.0.0.1:50670
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.basrikahveci.p2p.PeerRunner.handleCommand(PeerRunner.java:46) [p2p.jar:?]
	at com.basrikahveci.p2p.Main.main(Main.java:118) [p2p.jar:?]
Invalid input command:  connect 127.0.0.1:50670

I was confused about this

**Comment by yichaosun** [comment]
I have traced the source ,find your code split the command use ' ',not the ":" as specified in your help,
so I use the common 'connect hostname port'

I also want to know ,is this project completed? why we should to specified the ip and port,does not it should be automatic to connect each other ?

**Comment by metanet** [comment]
Hi @yichaosun

Thx for your bug report. I fixed the help text. The correct command is: `connect host port`. There is no ":" between the host and port information. 

I developed this project for a class I took a couple of years ago, and then open-sourced it. I have not done any more development on it afterwards. If you need such a tool, you can just fork the project and improve it as you wish. 

Regards,

**Comment by yichaosun** [comment]
Thx for your reply，I do interest in p2p which blockchain used, I wonder to know how p2p implement, I find that this project do not go through NAT for internet, maybe you can give me so direction or advice , I am new here ,and maybe you have found I poor with English,hahaha ,thx!!
